version: 2
updates:
- package-ecosystem: nuget
  directory: "/Sams2048.Logic"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - "samsmithnz"
- package-ecosystem: nuget
  directory: "/Sams2048.Tests"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - "samsmithnz"
- package-ecosystem: nuget
  directory: "/Sams2048.WPF"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - "samsmithnz"
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  assignees:
  - "samsmithnz"
